<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="icarus">
<xacro:property name="chassis_length" value = ".18"/>
<xacro:property name="chassis_width" value = ".203"/>
<xacro:property name="chassis_height" value = ".16"/>

<xacro:property name="wheel_radius" value = ".024"/>
<xacro:property name="wheel_width" value = ".03"/>
<xacro:property name="wheel_zoff" value = ".024"/>
<xacro:property name="wheel_ygap" value = ".024"/>
<xacro:property name="wheel_xoff" value = ".203"/>

<xacro:property name="support_height" value = ".203"/>
<xacro:property name="support_radius" value = ".203"/>


<link name="base_link">
    <visual>
        <geometry>
            <box size="${chassis_length}${chassis_width}${chassis_height} />
,,>        </geometry>

    </visual>
</link>

<!-- base_footprint has no visual but helps to determine where center of robot lies/>
<link name="base_footprint"/>

<joint name="base_joint" type="fixed"/>
    <parent link="base_link"/>
    <child link="base_footpriont"/>
    <origin xyz="0.0.0 ${-(wheel_radius+wheel_zof)}" rpy="0 0 0"/>
</joint>

<!-- wheels -->
<xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name = "${prefix}_link">
        <visual>
            <origin xyz=" 0 0 0" rpy "${pi/2} 0 0 "/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name=Gray">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="${prefix}_joint" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_link"
        <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(chassis_width/2 + wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
        axis xyz="0 1 0"/>
    </joint>
</xacro:macro>

<xacro:wheel prefix="frontLeft" x_reflect="0" y_reflect="0">
<xacro:wheel prefix="frontRight" x_reflect="0" y_reflect="0">
<xacro:wheel prefix="backLeft" x_reflect="-1" y_reflect="-1">
<xacro:wheel prefix="backLeft" x_reflect="-1" y_reflect="-1">